name: Copy the AADL Map

on:
  schedule:
    - cron: '0 */4 * * *'
  # For debug
  # push:
  #   branches:
  #     - main
jobs:
  download-and-save:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download file
        run: |
          curl -L -o map.json "https://aadl.org/summergame/map/data/SummerGame2024"

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A .
          if ! git diff --cached --quiet
          then
            git commit -m "Add downloaded file"
            git push
          else
            echo "No changes to commit"
          fi
