name: Run Kubra CLI and Commit JSON Output

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  get-map:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

    - name: Download file
      run: |
        curl -L -o map.json "https://aadl.org/summergame/map/data/SummerGame2023"

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git diff --exit-code --quiet
        then
          echo "No changes to commit"
        else
          git commit -m "Upadte map"
          git push